---
# molecule.yml for k3s_workers role
# Molecule testing configuration

driver:
  name: delegated
  options:
    managed: false

platforms:
  - name: k3s-worker-test

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        children:
          control_plane:
            hosts:
              k8-cp-1:
                ansible_host: 192.168.178.210
          workers:
            hosts:
              k8-wk-1:
                ansible_host: 192.168.178.220
                k3s_node_role: "worker"
    group_vars:
      all:
        k3s_version: "v1.30.6+k3s1"
        k3s_token: "test-token"

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy