---
# converge.yml for k3s_prerequisites role
# Applies the role

- name: Converge - Test k3s_prerequisites role
  hosts: all
  gather_facts: true
  become: false

  roles:
    - role: ../../../k3s_prerequisites