---
# Development environment secrets
# ENCRYPT THIS FILE: ansible-vault encrypt vault.yml
#
# vault_proxmox_api_host: pm02-dev
# vault_proxmox_api_user: root@pam
# vault_proxmox_api_token_id: ansible
# vault_proxmox_api_token_secret: "your-dev-token-here"